.travis.yml, src/Stan.hs, src/Stan/Analysis.hs, src/Stan/Partial.hs, src/Stan/Warning.hs, stan.cabal, test/Spec.hs
On current test file I got this output:
```
!!! Found 1 warning(s) in test/Spec.hs
Warning: Usage of the partial function ''head'
main = print $ head ["Hello"]
^^^^
```
=> Check on usage of partial functions

.stylish-haskell.yaml, app/Main.hs, src/Stan.hs, src/Stan/Cli.hs, stan.cabal
=> [#5] Create basic command line interface

src/Stan/Analysis.hs, stan.cabal
=> [#9] Count the number of analyzed modules

README.md, src/Stan.hs, src/Stan/Analysis.hs, src/Stan/Hie.hs, stan.cabal
=> [#4] Read hie files of the target project

src/Stan.hs, src/Stan/Hie/Debug.hs, stan.cabal
=> [#17] Create printing debugging functions for HieFile

src/Stan/Core/Id.hs, src/Stan/Hie/Debug.hs, src/Stan/Inspection.hs, src/Stan/Observation.hs, stan.cabal
=> [#16] Create core data types

src/Stan/Analysis.hs, src/Stan/Hie.hs, stan.cabal
=> [#13] Count the number of analysed source code lines

src/Stan.hs, src/Stan/Analysis.hs, src/Stan/Hie.hs, stan.cabal, test/Spec.hs, test/Test/Analysis.hs, test/Test/Example.hs
=> [#21] Add test on number of lines of code

.github/workflows/ci.yml, src/Stan/Core/Id.hs, src/Stan/Observation.hs, stan.cabal, target/Target/Example.hs, target/Target/HEAD.hs, test/Spec.hs, test/Test/Analysis.hs, test/Test/Analysis/Partial.hs, test/Test/Number.hs
=> [#7] Create automatic test

src/Stan.hs, src/Stan/Analysis/Partial.hs, src/Stan/Analysis/Pretty.hs, src/Stan/Inspection.hs, src/Stan/Observation.hs, stan.cabal, target/Target/Example.hs, test/Test/Analysis/Partial.hs, test/Test/Number.hs
=> [#8] Decide on the console output format

src/Stan/Category.hs, src/Stan/Inspection.hs, src/Stan/Observation.hs, stan.cabal, test/Test/Number.hs
=> [#25] Move 'Category' into separate module, introduce values, create list

src/Stan/Analysis/Partial.hs, src/Stan/Category.hs, src/Stan/Inspection.hs, src/Stan/Observation.hs, stan.cabal, test/Spec.hs, test/Test/Stan/Analysis.hs, test/Test/Stan/Analysis/Partial.hs, test/Test/Stan/Inspection.hs, test/Test/Stan/Number.hs
=> [#26] Smart constructors for 'Inspection' ids

src/Stan/Analysis/Partial.hs, src/Stan/Inspection.hs, src/Stan/Inspection/All.hs, src/Stan/Inspection/Partial.hs, src/Stan/Observation.hs, stan.cabal, test/Test/Stan/Analysis/Partial.hs, test/Test/Stan/Inspection.hs, test/Test/Stan/Number.hs
=> [#47] Restructure Inspections and Analysis

src/Stan/Category.hs, src/Stan/Inspection/All.hs, src/Stan/Inspection/Infinite.hs, src/Stan/Inspection/Partial.hs, stan.cabal, test/Test/Stan/Inspection.hs, test/Test/Stan/Number.hs
Introduces a new category of inspections.
=> [#40] Introduce 'Infinite' inspections

src/Stan/Analysis.hs, src/Stan/Analysis/Analyser.hs, src/Stan/Analysis/Partial.hs, src/Stan/Inspection.hs, src/Stan/Inspection/Infinite.hs, src/Stan/Inspection/Partial.hs, src/Stan/NameMeta.hs, stan.cabal, target/Target/Example.hs, test/Test/Stan/Analysis/Partial.hs, test/Test/Stan/Inspection.hs, test/Test/Stan/Number.hs
=> [#38] Add some partial functions Inspections

src/Stan/Inspection.hs, src/Stan/Inspection/Infinite.hs, src/Stan/Inspection/Partial.hs, src/Stan/Observation.hs, src/Stan/Severity.hs, stan.cabal, test/Test/Stan/Number.hs
=> [#30] Extend Severity data type

src/Stan/Analysis.hs, src/Stan/Analysis/Analyser.hs, src/Stan/Analysis/Infinite.hs, src/Stan/Analysis/Partial.hs, src/Stan/Inspection/Infinite.hs, src/Stan/Observation.hs, stan.cabal, target/Target/Infinite.hs, target/Target/Partial.hs, test/Spec.hs, test/Test/Stan/Analysis.hs, test/Test/Stan/Analysis/Common.hs, test/Test/Stan/Analysis/Infinite.hs, test/Test/Stan/Analysis/Partial.hs, test/Test/Stan/Number.hs
=> [#40] Add checks for the 'Infinite' group

src/Stan/Analysis/Pretty.hs, src/Stan/Observation.hs
=> [#34] Sort Observations by location

src/Stan/Analysis/Pretty.hs
=> [#43] Display the number of total checked inspections in the report

src/Stan/Analysis/Pretty.hs, src/Stan/Core/Id.hs, src/Stan/Inspection.hs, src/Stan/Inspection/All.hs, src/Stan/Inspection/Infinite.hs, src/Stan/Inspection/Partial.hs, stan.cabal, test/Test/Stan/Inspection.hs
=> [#31] Store inspections in 'HashMap'

src/Stan/Analysis/Analyser.hs, src/Stan/Analysis/Pretty.hs, src/Stan/Core/ModuleName.hs, src/Stan/NameMeta.hs, src/Stan/Observation.hs, stan.cabal, test/Test/Stan/Analysis/Common.hs, test/Test/Stan/Number.hs
Resolves #46
A bit more type-safety in the code :slightly_smiling_face:
=> [#46] Add 'Stan.Core.ModuleName'

src/Stan/Analysis.hs, src/Stan/Analysis/Analyser.hs, src/Stan/Analysis/Pretty.hs, src/Stan/Observation.hs, stan.cabal
=> [#34] Group observations into 'Slist'

src/Stan.hs, src/Stan/Cli.hs, src/Stan/Core/Id.hs, src/Stan/Inspection.hs, src/Stan/Inspection/All.hs
Resolves #36 
At the moment it has the following view (can be improved over time):
=> CLI command to show known Inspections

src/Stan.hs, src/Stan/Analysis/Pretty.hs, src/Stan/Cli.hs, src/Stan/Core/Toggle.hs, src/Stan/Observation.hs, stan.cabal, test/Test/Stan/Number.hs
=> [#33] Add --hide-solution option

src/Stan/Category.hs, src/Stan/Inspection.hs, src/Stan/Inspection/Infinite.hs, src/Stan/Inspection/Partial.hs, src/Stan/NameMeta.hs
=> [#70] Create lenses for Inspection and NameMeta

app/Main.hs, cabal.project, src/Stan.hs, src/Stan/Analysis.hs, src/Stan/Analysis/Pretty.hs, stan.cabal, test/Test/Stan/Analysis.hs
=> [#14] Count the number of used unique language extensions

src/Stan.hs, src/Stan/Observation.hs
=> [#75] Find filepath to cabal file

src/Stan/Analysis/Analyser.hs, src/Stan/Cli.hs, src/Stan/Hie/Match.hs, src/Stan/NameMeta.hs, stan.cabal, test/Test/Stan/Number.hs
=> [#58] Implement type search in HIE files

src/Stan/Analysis/Analyser.hs, src/Stan/Hie/Match.hs, src/Stan/Inspection.hs, src/Stan/Inspection/Infinite.hs, src/Stan/Inspection/Partial.hs, src/Stan/NameMeta.hs, target/Target/Infinite.hs, test/Test/Stan/Analysis/Infinite.hs
=> [#40] Inspections for partial functions on infinite lists

src/Stan/Inspection/Partial.hs, target/Target/Partial.hs, test/Test/Stan/Analysis/Infinite.hs, test/Test/Stan/Analysis/Partial.hs, test/Test/Stan/Number.hs
=> [#38] Inspections for partial functions

src/Stan/Hie/Match.hs, src/Stan/Inspection/Partial.hs, src/Stan/NameMeta.hs, target/Target/Partial.hs, test/Test/Stan/Analysis/Partial.hs, test/Test/Stan/Number.hs
=> [#41] Inspections for partial fs for some instances

src/Stan/Inspection.hs, src/Stan/NameMeta.hs, target/Target/Partial.hs, test/Test/Stan/Analysis/Common.hs, test/Test/Stan/Analysis/Infinite.hs, test/Test/Stan/Analysis/Partial.hs, test/Test/Stan/Number.hs
=> [#90] Automate inspection testing

cabal.project, src/Stan.hs, src/Stan/Analysis.hs, src/Stan/FileInfo.hs, stan.cabal, test/Test/Stan/Number.hs
=> [#76] Store file map in Analysis

src/Stan/Hie/Match.hs, target/Target/Infinite.hs
=> [#86] Handle `String` type alias as well as `[a]`

cabal.project, src/Stan.hs, src/Stan/Analysis.hs, src/Stan/Analysis/Pretty.hs, src/Stan/FileInfo.hs, src/Stan/Inspection.hs, stan.cabal, test/Test/Stan/Analysis.hs
=> [#96] Use latest version of extensions, support SafeHaskellExtensions

src/Stan.hs, src/Stan/Analysis/Pretty.hs, src/Stan/Cli.hs, src/Stan/Observation.hs, src/Stan/Report.hs, stan.cabal, test/Test/Stan/Number.hs
=> [#95] Create 'ReportSettings'

src/Stan/Analysis/Analyser.hs, src/Stan/Hie/Match.hs, src/Stan/Inspection.hs, src/Stan/Inspection/Infinite.hs, src/Stan/Inspection/Partial.hs, src/Stan/Pattern.hs, stan.cabal, test/Test/Stan/Number.hs
Resolves #97
Let me know what do you think and whether there're better ideas :slightly_smiling_face:
=> [#97] eDSL for 'Pattern'

src/Stan/Inspection/Partial.hs, src/Stan/NameMeta.hs, src/Stan/Pattern.hs
=> [#104] Simplify NameMeta API

src/Stan/Analysis/Analyser.hs, src/Stan/Hie/Match.hs, src/Stan/Inspection.hs, src/Stan/Inspection/Infinite.hs, src/Stan/Inspection/Partial.hs, src/Stan/Pattern/Type.hs, stan.cabal
Preparation before #107. Just an easy part with renaming. Sorry for taking too long to do this...
=> Rename 'Pattern' to 'PatternType'

cabal.project, stan.cabal
=> [#110] Use extensions from Hackage

src/Stan.hs, src/Stan/Cli.hs, test/Test/Stan/Analysis.hs
Resolves #94
This is basically multi-package projects support (I hope) :crossed_fingers:
=> [#94] Support multiple cabal files

src/Stan/Analysis/Analyser.hs, src/Stan/Core/List.hs, src/Stan/Hie/MatchAst.hs, src/Stan/Hie/MatchType.hs, src/Stan/NameMeta.hs, src/Stan/Pattern/Ast.hs, stan.cabal, test/Test/Stan/Number.hs
Resolves #107
I've implemented only types and a general matching function. To make sure that this works, an issue like #65 needs to be implemented. Probably some implementation details will change, but I decided to open a PR to show the general idea and use it in a separate PR with tests implementation.
=> [#107] Patterns for AST

src/Stan/Analysis/Analyser.hs, src/Stan/Category.hs, src/Stan/Hie.hs, src/Stan/Hie/MatchAst.hs, src/Stan/Inspection.hs, src/Stan/Inspection/All.hs, src/Stan/Inspection/AntiPattern.hs, src/Stan/Inspection/Infinite.hs, src/Stan/Inspection/Partial.hs, src/Stan/Pattern/Ast.hs, stan.cabal, target/Target/AntiPattern.hs, test/Test/Stan/Analysis.hs, test/Test/Stan/Analysis/AntiPattern.hs, test/Test/Stan/Analysis/Common.hs, test/Test/Stan/Number.hs
=> [#65] Find occurrences of [0 .. length xs]

src/Stan/Config.hs, stan.cabal, test/.stan-example.toml, test/Spec.hs, test/Test/Stan/Gen.hs, test/Test/Stan/Number.hs, test/Test/Stan/Toml.hs
=> [#121] Add config tests

src/Stan/Cli.hs, src/Stan/Severity.hs
Resolves #123
Implementation of CLI interface for specifying checks. Implements first option from the issue.
=> [#123] CLI for specifying checks

.github/workflows/ci.yml, cabal.project, src/Stan.hs, src/Stan/Cli.hs, src/Stan/Config.hs, src/Stan/Toml.hs, stan.cabal, test/Test/Stan/Toml.hs
Resolves #119
I see several issues with `Trial`:
* We actually don't always need `Last` logic in semigroup. for lists it should be (<>).
* We sometimes need to stop immediately still like when the specified file is not found).
Seems like we need to discuss more things in Trial...
=> [#119] Read the config files

src/Stan.hs, src/Stan/Cli.hs, src/Stan/Toml.hs
=> [#128] [#129] Add CLI option to ignore-default and use --config-file

cabal.project, src/Stan.hs, src/Stan/Cli.hs, src/Stan/EnvVars.hs, stan.cabal, test/Test/Stan/Number.hs
=> [#133] Support ENV Vars

src/Stan.hs, src/Stan/Cli.hs, src/Stan/Config.hs
=> [#134] Command to turn TOML config into CLI line to use

src/Stan/Cli.hs, src/Stan/Config.hs, stan.cabal, test/Spec.hs, test/Test/Stan/Cli.hs, test/Test/Stan/Number.hs
=> [#145] Tests for `toml-to-cli` command

src/Stan/Config.hs, test/Test/Stan/Cli.hs, test/Test/Stan/Gen.hs, test/Test/Stan/Toml.hs
Resolves #147
Already found a :beetle:
=> [#147] Property tests for `toml-to-cli` command

src/Stan/Cli.hs, src/Stan/Config.hs, src/Stan/Toml.hs, test/Test/Stan/Gen.hs
=> [#142] Remove 'CheckScopeModule' from Config

src/Stan.hs, src/Stan/Analysis.hs, src/Stan/Config.hs, test/Test/Stan/Analysis.hs
=> [#148] Use applyChecks in analysis functions

src/Stan/Analysis.hs, src/Stan/Analysis/Pretty.hs
=> [#154] Count total number of inspections

src/Stan.hs, src/Stan/Analysis.hs, src/Stan/Cabal.hs, stan.cabal, test/Test/Stan/Number.hs
=> [#115] Move Cabal-related handling into the 'Stan.Cabal' module

src/Stan/Config.hs, stan.cabal, test/Spec.hs, test/Test/Stan/Config.hs, test/Test/Stan/Number.hs
=> [#144] Write docs for applyCheck

src/Stan/Config.hs, test/Test/Stan/Config.hs, test/Test/Stan/Gen.hs
=> [#150] Property test on double applyChecks

src/Stan/Cli.hs, src/Stan/Config.hs, src/Stan/Toml.hs, test/.stan-example.toml, test/Test/Stan/Cli.hs, test/Test/Stan/Gen.hs, test/Test/Stan/Toml.hs
in Config for ignoring observations
Resolves #143
=> [#143] Remove 'CheckObservation' filter and create a separate field

.stan.toml, src/Stan.hs, src/Stan/Config.hs, test/Test/Stan/Config.hs
=> [#165] Use `removed` Config field before analysis

src/Stan.hs, src/Stan/Analysis.hs, src/Stan/Analysis/Pretty.hs, src/Stan/Observation.hs, test/Test/Stan/Analysis.hs
=> [#166] Use `observations` Config field after analysis

src/Stan/Analysis/Analyser.hs, src/Stan/Hie/MatchAst.hs, src/Stan/Hie/MatchType.hs, src/Stan/Inspection/AntiPattern.hs, src/Stan/Inspection/Infinite.hs, src/Stan/Inspection/Partial.hs, src/Stan/Pattern/Ast.hs, src/Stan/Pattern/Edsl.hs, src/Stan/Pattern/Type.hs, stan.cabal, target/Target/Partial.hs, test/Test/Stan/Analysis/AntiPattern.hs, test/Test/Stan/Analysis/Common.hs, test/Test/Stan/Analysis/Partial.hs, test/Test/Stan/Number.hs
Resolves #106
Resolves #193 
The PR implements eDSL for boolean patterns, but currently I can't use them :disappointed:
=> [#106] Patterns boolean algebra

src/Stan/Cabal.hs, src/Stan/Inspection/AntiPattern.hs, src/Stan/Inspection/Infinite.hs, src/Stan/Inspection/Partial.hs, stan.cabal
=> [#197] Use relude-0.7.0.0

src/Stan/Category.hs, src/Stan/Inspection.hs, src/Stan/Inspection/AntiPattern.hs, target/Target/AntiPattern.hs, test/Test/Stan/Analysis/AntiPattern.hs
=> [#99] Inspection on foldl

src/Stan/Inspection/AntiPattern.hs, stan.cabal, target/Target/AntiPattern.hs, test/Test/Stan/Analysis/AntiPattern.hs
=> [#99] Anti-pattern: slow HashMap.size

src/Stan.hs, src/Stan/Cli.hs
Resolves #195
That was quite straightforward, thanks to `tomland` and previous work by @vrom911 :slightly_smiling_face:
=> [#195] Implement `cli-to-toml` command

src/Stan/Analysis/Pretty.hs
=> [#182] Calculate project health

src/Stan/Analysis/Pretty.hs, src/Stan/FileInfo.hs, src/Stan/Report/Css.hs, src/Stan/Report/Html.hs
=> [#202] Add extensions info in the report

src/Stan/Analysis/Summary.hs, src/Stan/Category.hs, src/Stan/Core/ModuleName.hs, src/Stan/Report/Html.hs, src/Stan/Severity.hs, stan.cabal, test/Test/Stan/Number.hs
=> [#190] Create Summary Section

src/Stan/Hie/Debug.hs, stan.cabal
=> [#230] Remove the 'ghc-paths' dependency and the 'printHieAsts' function

src/Stan/Analysis/Analyser.hs, src/Stan/Inspection.hs, src/Stan/Inspection/AntiPattern.hs, src/Stan/Inspection/Infinite.hs, src/Stan/Inspection/Partial.hs, test/Test/Stan/Analysis/Common.hs
=> [#237] Simplify the 'InspectionAnalysis' data type

src/Stan/Hie/Debug.hs, src/Stan/Inspection/AntiPattern.hs, src/Stan/Pattern/Type.hs, target/Target/AntiPattern.hs, test/Test/Stan/Analysis/AntiPattern.hs
=> [#176] Foldable methods on possibly error-prone structures

src/Stan/Inspection.hs, src/Stan/Inspection/AntiPattern.hs, src/Stan/Inspection/Infinite.hs, src/Stan/Inspection/Partial.hs, src/Stan/NameMeta.hs, src/Stan/Pattern/Ast.hs, target/Target/AntiPattern.hs, target/Target/Infinite.hs, target/Target/Partial.hs, test/Test/Stan/Analysis.hs, test/Test/Stan/Analysis/AntiPattern.hs, test/Test/Stan/Analysis/Common.hs, test/Test/Stan/Analysis/Infinite.hs, test/Test/Stan/Analysis/Partial.hs, test/Test/Stan/Number.hs
=> [#87] Handle multiple definitions for Inspection

.github/workflows/ci.yml, src/Stan/NameMeta.hs
=> [#240] Bypass Cabal hack on MacOS

src/Stan.hs, src/Stan/Inspection/Infinite.hs
=> [#44] Exit with failure when the list of observations is not empty

src/Stan/Hie.hs
Resolves #116
Added a few friendlier messages :slightly_smiling_face:
=> [#116] Better error message when 'stanArgsHiedir' is not found

src/Stan/Analysis/Analyser.hs, src/Stan/Inspection.hs, src/Stan/Inspection/Style.hs, src/Stan/Pattern/Ast.hs, target/Target/Style.hs, test/Test/Stan/Analysis/Style.hs
=> [#172] Inspection: big tuples

src/Stan/Hie/MatchAst.hs, src/Stan/Inspection/AntiPattern.hs, src/Stan/NameMeta.hs, src/Stan/Pattern/Ast.hs, src/Stan/Pattern/Type.hs, stan.cabal, target/Target/AntiPattern.hs, test/Test/Stan/Analysis/AntiPattern.hs
=> [#99] Inspections for known anti-patterns

src/Stan/Cli.hs
Question: should we use colours and any other formatting? I tried bold on commands now, could you please check it out and leave your feedback on how it looks.
On a bigger note, unfortunately, the `optparse-applicative` library's functional is not very flexible in prettifying meaning. Very limited amount of pieces can be configured and absolutely no possibility to change the Usage section
=> [#130] Some CLI improvements

.stan.toml, src/Stan/Cabal.hs, src/Stan/Category.hs, src/Stan/Inspection/AntiPattern.hs, stan.cabal, target/Target/AntiPattern/Stan0212.hs, test/Test/Stan/Analysis/AntiPattern.hs
=> [#255] Forbid unsafe functions that could lead to errors

.github/workflows/ci.yml, src/Stan.hs, src/Stan/Analysis.hs, src/Stan/Analysis/Analyser.hs, src/Stan/Cabal.hs, src/Stan/Core/ModuleName.hs, src/Stan/Ghc/Compat.hs, src/Stan/Hie.hs, src/Stan/Hie/Compat.hs, src/Stan/Hie/Debug.hs, src/Stan/Hie/MatchAst.hs, src/Stan/Hie/MatchType.hs, src/Stan/NameMeta.hs, src/Stan/Observation.hs, src/Stan/Pattern/Ast.hs, src/Stan/Pattern/Edsl.hs, stan.cabal, test/Test/Stan/Analysis/Infinite.hs
Resolves #242
That was unexpectedly easy...
=> [#242] Support GHC-8.10

cabal.project, src/Stan.hs, src/Stan/Config/Pretty.hs
=> [#256] Clean up CLI output

src/Stan.hs, src/Stan/Cli.hs, src/Stan/Inspection.hs
=> [#261] Generate md with all inspections

src/Stan/Inspection/AntiPattern.hs, src/Stan/Inspection/Infinite.hs, src/Stan/Inspection/Partial.hs
Let me know if you find those solutions reasonable.
=> Add more solutions to some problems

src/Stan/Analysis/Analyser.hs, src/Stan/EnvVars.hs, src/Stan/Hie/MatchAst.hs, src/Stan/Inspection.hs, src/Stan/Inspection/AntiPattern.hs, src/Stan/Pattern/Ast.hs, src/Stan/Toml.hs, stan.cabal, target/Target/AntiPattern/Stan0213.hs, test/Test/Stan/Analysis/AntiPattern.hs, test/Test/Stan/Cli.hs, test/Test/Stan/Toml.hs
=> [#264] Inspection on `_` pattern-matching for sum types

src/Stan/Analysis/Analyser.hs, src/Stan/Core/List.hs, src/Stan/Hie.hs, src/Stan/Hie/MatchAst.hs, src/Stan/Inspection.hs, src/Stan/Inspection/AntiPattern.hs, src/Stan/NameMeta.hs, src/Stan/Pattern/Ast.hs, src/Stan/Pattern/Type.hs, stan.cabal, target/Target/AntiPattern/Stan0214.hs, test/Test/Stan/Analysis/AntiPattern.hs, test/Test/Stan/Analysis/Common.hs
=> [#173] Inspection: replace multiple comparison operations with operators

src/Stan/Ghc/Compat.hs, src/Stan/Observation.hs
=> [#267] Support reporting of multi-line observations

test/Test/Stan/Analysis/AntiPattern.hs, test/Test/Stan/Analysis/Common.hs, test/Test/Stan/Analysis/Infinite.hs, test/Test/Stan/Analysis/Partial.hs, test/Test/Stan/Analysis/Style.hs
=> [#268] Simplify modules and files names necessity in tests

src/Stan/NameMeta.hs
=> [#274] Bypass Cabal hack on Windows

.github/workflows/ci.yml, .gitignore, .stan-windows.toml, src/Stan/Inspection/AntiPattern.hs, stack.yaml, test/Spec.hs, test/Test/Stan/Analysis.hs, test/Test/Stan/Analysis/Common.hs
=> [#247] Build with everything on CI

src/Stan/Hie/MatchAst.hs, src/Stan/Inspection/AntiPattern.hs, src/Stan/Pattern/Ast.hs, target/Target/AntiPattern.hs, test/Test/Stan/Analysis/AntiPattern.hs
=> [#275] Inspection: invalid file paths on Windows

cabal.project, src/Stan.hs, src/Stan/Cli.hs, src/Stan/Toml.hs, stack.yaml
=> [#281] Use newer trial version

README.md
=> [#177] Write juicy README

app/Main.hs
=> [#312] Set encoding locale to utf8

stan.cabal
Closes #316
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kowainik/stan/317)
=> Include test data files in the source distribution

src/Stan/Inspection/AntiPattern.hs
"bytesting" is missing a letter
=> Fix typo in package

CHANGELOG.md, src/Stan/Hie.hs, src/Stan/Hie/MatchAst.hs, src/Stan/Observation.hs, stan.cabal
=> [#327] Print <UNAVAILABLE> when HIE files are incomplete instead of failing

README.md
=> [#309] Missing documentation on ignoring inspections

CHANGELOG.md, src/Stan/Analysis/Analyser.hs, src/Stan/Hie/Compat.hs, src/Stan/Hie/MatchAst.hs, src/Stan/Pattern/Ast.hs, target/Target/AntiPattern/Stan0206.hs, test/Test/Stan/Analysis.hs, test/Test/Stan/Analysis/AntiPattern.hs
=> [#326] Handle constraints before constructors in STAN-0206 

CHANGELOG.md, README.md, src/Stan.hs, src/Stan/Analysis/Pretty.hs, src/Stan/Browse.hs, src/Stan/Cli.hs, src/Stan/Observation.hs, src/Stan/Report/Settings.hs, stan.cabal
=> [#320] Add `-b|--browse` option to the report command

CHANGELOG.md, README.md, src/Stan.hs, src/Stan/Analysis.hs, src/Stan/Cabal.hs, src/Stan/Category.hs, src/Stan/Cli.hs, src/Stan/Core/Id.hs, src/Stan/Core/ModuleName.hs, src/Stan/FileInfo.hs, src/Stan/Inspection.hs, src/Stan/Observation.hs, src/Stan/Severity.hs, src/Stan/Toml.hs, stack.yaml, stan.cabal, test/Test/Stan/Analysis.hs
=> [#323] Add a JSON output format

src/Stan/Analysis.hs, src/Stan/Analysis/Pretty.hs, src/Stan/Observation.hs, src/Stan/Report/Html.hs, test/Test/Stan/Analysis/Common.hs
=> [#335] Add srcSpan start/end col/line separately in JSON for Observation

.github/workflows/ci.yml, .github/workflows/release.yml, CHANGELOG.md, stan.cabal
=> [#337] Implement binary releases on CI

README.md
=> [#339] Configure Stan installation on macOS with `brew`

README.md
=> [#338] Configure Stan installation for the Ubuntu

CHANGELOG.md, src/Stan/Analysis.hs, src/Stan/Analysis/Analyser.hs, src/Stan/Analysis/Visitor.hs, stan.cabal
Resolves #55
This actually speeded up the performance a lot! I tested on the `agda` repository.
* Previous version: 30s
* New version: 16s
=> [#55] Single-pass functions detection in Analysis

CHANGELOG.md, src/Stan/Inspection/AntiPattern.hs, stack.yaml
=> [#368] Update 'unordered-containers' inspections

.github/workflows/ci.yml, README.md
=> [#402] Update the default branch to main

.github/workflows/ci.yml, .github/workflows/release.yml, stack.yaml, stan.cabal
Resolves #414
Resolves #408
Here is the cron expression I used:
* https://crontab.guru/every-week
And here is the documentation on all events for a pull request opening:
* https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
=> [#414] Update GitHub Actions template

.github/workflows/ci.yml, README.md, stan.cabal
Adding some more information to README (our talk, known users).
Also attempted to fix the CI for HLint by pinning the HLint version and by downloading it from its binary releases.
=> Update README, fix HLint CI

stan.cabal
Fixes https://github.com/kowainik/stan/issues/539
=> Bump pretty-simple
