src/Stan.hs
src/Stan/Analysis.hs
src/Stan/Analysis/Partial.hs
src/Stan/Cli.hs
src/Stan/Hie/Debug.hs
src/Stan/Inspection.hs
src/Stan/Observation.hs
stan.cabal
test/Test/Analysis.hs

Resolves #6
It worked! On my local test case I saw this output:
```haskell
Analysis
{ analysisModuleCount = 12
, analysisLinesOfCode = 0
, analysisUsedExtensions = 0
, analysisObservations =
[ Observation
{ observationId = Id {unId = ""}
, observationInspectionId = Id {unId = "HEAD"}
, observationLoc = SrcSpanOneLine "app/Main.hs" 7 7 21
, observationFile = "app/Main.hs"
}
]
}
```

[#6] Check for usage of 'head' for lists

---

src/Stan.hs
src/Stan/Analysis/Analyser.hs
test/Test/Stan/Analysis/Infinite.hs

Resolves #53
AST node looks like this:
```haskell
, nodeIdentifiers = fromList
[
( Right $base$Data.OldList$genericLength
, IdentifierDetails
{ identType = Nothing
, identInfo = fromList [ IEThing Import ]
}
)
]
```
Each identifier contains a `Set` of some [`ContextInfo`](https://downloads.haskell.org/~ghc/8.8.3/docs/html/libraries/ghc-8.8.3/HieTypes.html#t:ContextInfo). So I'm just checking that this name doesn't come under the `Import` context.

[#53] Don't find identifier usages in imports

---

src/Stan/Analysis/Analyser.hs
src/Stan/Observation.hs
stan.cabal
test/Spec.hs
test/Test/Stan/Analysis/Common.hs
test/Test/Stan/Analysis/Infinite.hs
test/Test/Stan/Analysis/Partial.hs
test/Test/Stan/Number.hs
test/Test/Stan/Observation.hs

Resolves #32
Now Observation ID looks like this:

[#32] Stable ids for Observations

---

src/Stan/Inspection/Partial.hs
target/Target/Partial.hs
test/Test/Stan/Analysis/Partial.hs
test/Test/Stan/Number.hs

A few more checks.
The implementation is more verbose this time since data types, modules and solutions are completely different. I'm thinking, that maybe adding lenses to `Inspection` and `NameMeta` data types can help us with reducing boilerplate. What do you think?

[#38] Add partial inspections for 'fromJust' and 'read'

---

.stan.toml
src/Stan/Config.hs
src/Stan/Severity.hs
src/Stan/Toml.hs
stan.cabal
test/Test/Stan/Number.hs

Resolves #24
This PR introduces `Config` data types and TOML codecs.
I will add the logic of reading config and tests separately.
I changed the types a bit in order to preserve the users' order, let me know if it still looks okay, @chshersh

[#24] Create configuration

---

src/Stan/NameMeta.hs

Resolves #109
Turned out, the `nameModule` function is partial :unamused:

[#109] GHC panic in 'nameModule'

---

.github/workflows/ci.yml

Now CI will rebuild from scratch each time dependencies are changed. But at least new cache will be uploaded.

Cache 'cabal freeze' output on CI

---

src/Stan.hs
src/Stan/Cli.hs
src/Stan/Toml.hs
test/Test/Stan/Toml.hs

Resolves #135
I've also changed logic for default file read for TOML a bit. Now it first checks the file `.stan.toml` in the current dir, and if it is not found checks the file in the home dir.

[#135] Combine CLI options and Config options using 'trial'

---

src/Stan/Config.hs
src/Stan/Inspection/All.hs

Resolves #120
The logic might be complicated, but I've tried to write it cleanly. Any suggestions are appreciated :slightly_smiling_face: I've decided that usage of config should be implemented in a separate issue. And I will write tests once we resolve all open questions...
**Open questions:**
1. When I work only with `[FilePath]`, I don't have info about `ModuleName`, so I can't easily apply `CheckScopeModule`...
2. Our config allows ignoring `Id Observation`. But when working only with `Inspection`, we don't have `Observation`. So our filtering should actually has 2 phases:
1. First, we get for files only those `Inspections` we want to run.
2. Once we get resulting observations, we should filter by observations. In this case, `HashMap FilePath (HashSet (Id Inspection))` should be …

[#120] Create the data type to accumulate and aply config info

---

src/Stan/Cli.hs
src/Stan/Config.hs
src/Stan/Toml.hs
test/Test/Stan/Cli.hs
test/Test/Stan/Config.hs
test/Test/Stan/Gen.hs
test/Test/Stan/Toml.hs

Resolves #158
I have renamed `CheckScope` -> `Scope`.
I will add `remove` tests later. For now at least property tests still pass, so it should be ok :)

[#158] Add `remove` field in the Config

---

src/Stan/Analysis/Analyser.hs
src/Stan/Category.hs
src/Stan/Hie/MatchAst.hs
src/Stan/Inspection.hs
src/Stan/Inspection/All.hs
src/Stan/Inspection/Style.hs
src/Stan/Pattern/Ast.hs
stan.cabal
target/Target/Style.hs
test/Test/Stan/Analysis.hs
test/Test/Stan/Analysis/Style.hs
test/Test/Stan/Number.hs

Resolves #100
A new inspection looks like this:
The heaviest module is `Stan.Analysis.Analyser`. It contains the main logic for processing the AST and collecting all operators.
What else is done:
* New `Stan.Inspection.Style` module for the `Style :: Severity` inspections
* New constructor to `PatternAst` to match on any number of children nodes
* New AST patterns to handle fixities
Open questions and what else needs to be done:
1. More tests when the inspection doesn't trigger?
2. Currently, doesn't handle operators as a part of typeclasses (no warning on `(?)` from `PatternBool` eDSL).
3. Also warns on operators inside `where`.

[#100] Inspection: missing `infix` for operator

---

src/Stan/Analysis.hs
src/Stan/Analysis/Analyser.hs
src/Stan/Cli.hs
src/Stan/Config.hs
src/Stan/FileInfo.hs
src/Stan/Inspection.hs
src/Stan/Inspection/AntiPattern.hs
src/Stan/Pattern/Ast.hs
src/Stan/Pattern/Type.hs
stan.cabal
target/Target/AntiPattern/Stan0206.hs
target/Target/AntiPattern/Stan0206Extensions.hs
test/Test/Stan/Analysis.hs
test/Test/Stan/Analysis/AntiPattern.hs
test/Test/Stan/Number.hs

Resolves #171
This was tough :sweat: 
Implemented inspection for finding lazy fields and producing a warning on them. Current limitation: ignores `data` with a single field. HIE AST doesn't track difference between `newtype` and `data`, so some workarounds involved.
TODO:
* Fix warnings for our own code (make all fields strict in all data types). The inspection has already proven itself handy!

[#171] Inspection: strict data type fields

---

.github/workflows/ci.yml

Speed up numbers:
* Build takes approximately the same time: 1m33s
* Tests are now 2 seconds instead of 9
* Dogfooding is 1 second instead of 9

Try to speed up CI a bit

---

CHANGELOG.md
src/Stan/Cli.hs
src/Stan/Info.hs

Resolves #329
`base` doesn't include a minor version of GHC. I've created an issue in GHC for further improvements:
* https://gitlab.haskell.org/ghc/ghc/-/issues/18403

[#329] Add GHC version to the --version output

---

src/Stan/Analysis/Pretty.hs

I am pretty sure that this is a typo: `SafeHaskel -> SafeHaskell` 😄

Fix typo in Pretty.hs

---

README.md

I believe that there's a typo in the table which explains various sub-commands. The given `check` command involves the the `--scope=all` flag, which doesn't exist:
```bash
$ stan check --exclude --category=Infinity --scope=all check --include --id "STAN-0101" --file=src/Main.hs
Invalid option `--scope=all'
Did you mean this?
--scope-all
```
The `-` and `=` keys are right next to each other, which makes me think it's a typo.
This is my first time contributing. The contributing guidelines say to first create an issue... but this is a minuscule fix (it's a single character!). Please let me know if you'd rather I bundle this with an issue and I will do so.
Thank you for making Stan!

Fix --inspect-all argument typo in README.md

---

stack.yaml

Just bumping the resolver to the latest LTS available on stackage. Builds fine, and tests are passing.

Update resolver to the latest LTS

---

stan.cabal

Simplified the stan.cabal file a little bit after upgrading to a newer `relude`. Just noticed a few minor improvements.

Cleanup stan.cabal file

---

stack.yaml

I upgraded stack lts version to 18.18 to use `stan` on GHC 8.10.7.
I'm not sure I handled correctly the version changes correctly.
Feel free to ditch this PR, or to suggest how to handle things correctly

upgrade stack lts to 18.18

---

.github/workflows/release.yml

Because the older version was using deprecated functionality.  The error message was:
Error: Unable to process command '##[set-env
name=GIT_TAG_NAME;]0.1.0.0' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Bump olegtarasov/get-tag

---

src/Stan/Ghc/Compat810.hs
src/Stan/Hie.hs
src/Stan/Hie/MatchAst.hs
src/Stan/Pattern/Ast.hs
src/Stan/Pattern/Type.hs

These changes avoid almost all GHC warnings on building. The one warning I could not work out how to avoid was:
~~~text
<no location info>: warning: [-Wunused-packages]
The following packages were specified via -package or -package-id flags,
but were not needed for compilation:
- base-4.17.2.0 (exposed by flag -package-id base-4.17.2.0)
~~~

Changes to avoid GHC warnings on building

---

stack.yaml
stan.cabal

`stack.yaml` is bumped to GHC 9.4.7, the most recent version of GHC supported by the tool.
`stack.yaml` is incuded in the sdist file. This will help Stack users install the tool from Hackage.
(As an aside, the current `stack.yaml` file will not work because it does not set the flags required for its `mintty` dependency. That falls away if this pull request is adopted.)

Bump `stack.yaml`, include in sdist file

---

src/Stan/Pattern/Type.hs

This solution uses a single `#if #elif #endif` (rather than the existing two) and moves all the affected code within each limb. It also allows for some simplication within each limb.

Avoid GHC warnings about 'Defined but not used'

---

.github/workflows/ci.yml

To explain:
* Bumps to GHC 9.4.7 (the version specified by the `stack.yaml`).
* Adds a 'cache-bust' to the caching key (in case it is needed in the future).
* Uses the stack.yaml for the key, not the GHC version.
* Uses the Stack-supplied GHC (which will be cached). `--system-ghc` does nothing, if the system's GHC is not the version that Stack requires. So, Stack will have been fetching the required GHC in any event (given the `stack.yaml`).
* Uses `stack exec` rather than `stack run`, as we know the executable has already been built.
* Specifies `--cabal-file-path stan.cabal` in case other Cabal files are added in the future and to save stan from searching for Cabal files.

Revisit Stack-related CI job

---

src/Stan/Ghc/Compat.hs
src/Stan/Ghc/Compat906.hs
src/Stan/Hie/Compat.hs
src/Stan/Hie/Compat904.hs
src/Stan/Hie/Debug.hs
src/Stan/Hie/Debug902.hs
stan.cabal

- Bump dependencies.
- Add Debug908.hs
- Fix renaming of `(,)` to `Tuple2` from `GHC.Tuple.Prim` (https://hackage.haskell.org/package/ghc-prim-0.11.0/docs/GHC-Tuple-Prim.html#t:Tuple2)
- Set conditional `--allow-newer` for ci

Support GHC 9.8

---

.github/workflows/ci.yml

 Fixing Github actions caching (issue #529)

---

.github/workflows/ci.yml

Closes https://github.com/kowainik/stan/issues/535
This removes the special case code added in
aff7e69d671d22fde0a0236e6bd511804c0605af because at that time stan's depedencies had not yet had their bounds adjusted to support GHC 9.8. Now they do support 9.8 so we can remove the special case.

Remove CI special case for GHC 9.8

---

src/Stan/Hie.hs
src/Stan/Hie/Compat900.hs
src/Stan/Hie/Compat902.hs
src/Stan/Hie/Compat904.hs
stan.cabal

Fixes run time error: `nodeInfo`

Merge SourceInfo and GeneratedInfo correctly

---

src/Stan.hs

This is no much more than anything a separation of functions, so that `stan` functionality can be better added to the `hls-stan-plugin` (https://github.com/haskell/haskell-language-server/pull/3914). 
`getStanConfig` is the only essential one for the plugin. I factored-out the second `getAnalysis` to use it as-is for `hls`. However, that is not possible because all the internal machinery in `stan` works with __only__ relative paths, while the plugin at the end requires an absolute path. I'm inclined to leave it as is, but if it were possible to change `stan` internals to get one version of the function with both the plugin and `stan` itself, that would be nicer.
This also exports `runStan`, but it would be no problem leaving it there.

Break up runStan function and expose it and its components

---

stack-ghc-9.6.3.yaml
stan.cabal

Also bumps old `stack.yaml` to `lts-22.6` (the last for GHC 9.6.3) and preserves it, for people using Stan with GHC 9.6.3 and Stack in CI.

Bump stack.yaml to GHC 9.6.4/lts-22.7

---

.github/workflows/ci.yml
stack-ghc-9.6.4.yaml
stack.yaml
stan.cabal

Also bumps old `stack.yaml` to `lts-22.20` (the last for GHC 9.6.4) and preserves it, for people using Stack with GHC 9.6.4 and Stack in CI.
Also updates `stack-ghc-9.6.3.yaml` for Cabal file revisions made to `extensions-0.1.0.1`.
Also bumps the Stack-related part of the CI.

Bump stack.yaml to GHC 9.6.5/lts-22.21

---

stan.cabal

because we already constrain it in the library

Don't constrain filepath in the tests

---

stan.cabal

I had a go a fixing this by only depending on base in components that needed it. After commenting out all other components except the main library, I found that base was needed and the `-Wunused-packages` warning was a false positive. Rather than removed the `-Wunused-packages` warning, I opted to leave a comment pointing to the relevant GHC issue.

Warning about overzealous -Wunused-packages

---

src/Stan/Core/Id.hs
src/Stan/Example.hs
src/Stan/Ghc/Compat902.hs
src/Stan/Ghc/Compat906.hs
src/Stan/Hie/Debug810.hs
src/Stan/Hie/Debug900.hs
src/Stan/Hie/Debug902.hs
src/Stan/Hie/Debug908.hs
target/Target/AntiPattern.hs
target/Target/AntiPattern/Stan0206.hs
target/Target/AntiPattern/Stan0206Extensions.hs
target/Target/AntiPattern/Stan0212.hs
target/Target/AntiPattern/Stan0213.hs
target/Target/AntiPattern/Stan0214.hs
target/Target/Infinite.hs
target/Target/Partial.hs
target/Target/Style.hs

Replace -fno-warn with -Wno

---

src/Stan/Report/Html.hs

For the `ghc-9.10.1` build we can pick up `blaze-html-0.9.2.0` but with it get a `-Wname-shadowing` warning. This fixes that and I opted to rename `s` locally rather than use `CPP` with the import.
https://hackage.haskell.org/package/blaze-html-0.9.2.0/changelog
https://hackage.haskell.org/package/blaze-html-0.9.2.0/docs/Text-Blaze-Html4-FrameSet.html#v:s

Avoid -Wname-shadowing with Text.Blaze.Html5.s

---

src/Stan/Inspection/Partial.hs
src/Stan/Pattern/Type.hs
stan.cabal
target/Target/Partial.hs
test/Test/Stan/Analysis.hs
test/Test/Stan/Analysis/Partial.hs
test/Test/Stan/Number.hs

I added four new inspections, all relating to functions on `Scientific` from the `scientific` package that are partial due to potentially repeating decimals:
- STAN-0022 `fromRational :: Rational -> Scientific`
- STAN-0023 `realToFrac :: Real a => a -> Scientific`
- STAN-0024 `recip :: Scientific -> Scientific`
- STAN-0025 `(/) :: Scientific -> Scientific -> Scientific`

[#578] Adds inspections for partial `Scientific` functions
